countries:
  - POLCPIALLMINMEI   # Poland CPI
  - CP0000HRM086NEST  # Croatia CPI
  - SAUCPALTT01IXOBM  # Saudi Arabia CPI
  - CPALTT01JPM661S   # Japan CPI
  - CANCPALTT01IXOBSAM  # Canada CPI
  - CP0000BGM086NEST  # Bulgaria CPI
  - CP0000TRM086NEST  # Turkey CPI
  - CP0000LTM086NEST  # Lithuania CPI
  - CP0000ROM086NEST  # Romania CPI
  - CP00MI15ALM086NEST # Albania CPI
  - CP00MI15XKM086NEST # Kosovo CPI 
  - CP0000EZ19M086NEST  # EA19 CPI
  - CZECPIALLMINMEI   # Czechia CPI
  - SVKCPIALLMINMEI   # Slovak CPI
  - CHECPIALLMINMEI   # Switzerland CPI
  - ZAFCPIALLMINMEI   # South Africa CPI
  - INDCPIALLMINMEI   # India CPI
  - RUSCPIALLMINMEI   # Russia CPI
  - CHLCPIALLMINMEI   # Chile CPI
  - GBRCPIALLMINMEI   # UK CPI
  - DNKCPIALLMINMEI   # Denmark CPI
  - GRCCPIALLMINMEI   # Greece CPI
  - BELCPIALLMINMEI   # Belgium CPI
  - PRTCPIALLMINMEI   # Portugal CPI
  - HUNCPIALLMINMEI   # Hungary CPI
  - ISRCPIALLMINMEI   # Israel CPI
  - DEUCPIALLMINMEI   # German CPI
  - BRACPIALLMINMEI   # Brazil CPI
  - FRACPIALLMINMEI   # France CPI
  - CHNCPIALLMINMEI   # China CPI
  - ITACPIALLMINMEI   # Italy CPI
  - MEXCPIALLMINMEI   # Mexico CPI
  - IDNCPIALLMINMEI   # Indonesia CPI
  - SWECPIALLMINMEI   # Sweden CPI
  - ESPCPIALLMINMEI   # Spain CPI
  - CPIAUCSL          # USA CPI
  - CPILFESL          # USA Core CPI
  - PCEPI             # USA PCE
  - PCEPILFE          # USA Core PCE

lags: 4                      # Number of lagged values to include as features
rolling_window_size: 240     # Rolling training window (in months)
min_train_observations: 24   # Minimum required training obs for the target country
